# Generated by Django 3.2.7 on 2021-09-08 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='valid_upto',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 8, 21, 11, 59, 986667)),
        ),
    ]
