# Generated by Django 3.2.7 on 2021-09-08 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_otp_valid_upto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='valid_upto',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 8, 23, 14, 38, 691246)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
